# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports: 
      - "3002:3306"
    environment:
      MYSQL_DATABASE: cigarApp
      MYSQL_ROOT_PASSWORD: toor
